<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ArticleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('article')->insert([
            'title' => "Aurelia Aurita",
            'contentId' => json_encode([
                "Para1" => "Aurelia aurita (juga dikenal dengan ubur-ubur bulan) adalah spesies yang dipelajari secara luas dari genus Aurelia. Semua spesies dalam genus saling berkaitan erat, dan sulit untuk mengidentifikasi medusa Aurelia tanpa pengambilan sampel genetik, sebagian besar apa yang berlaku sama bagi semua spesies dalam genus. Ubur-ubur ini tampak tembus pandang, biasanya berukuran sekitar 25-40 cm, dan dapat diidentifikasi oleh empat gonad berbentuk tapal kuda, mudah dilihat melalui bagian atas bel. Ubur-ubur ini makan dengan mengumpulkan medusa, plankton, dan moluska dengan tentakelnya, dan membawa mangsanya ke dalam tubuh untuk dicerna. Ubur-ubur ini hanya mampu bergerak terbatas, dan hanyut dengan arus, bahkan ketika berenang. Genus Aurelia ditemukan di hampir seluruh lautan di dunia, dari daerah tropis ke utara sejauh 70°LU dan ke selatan sejauh 40°LS. Spesies Aurelia aurita yang ditemukan di sepanjang pantai Atlantik timur Eropa Utara dan pantai Atlantik barat Amerika Utara di New England dan Kanada Timur. Secara umum, Aurelia hidup di perairan pantai yang dapat ditemukan di muara sungai dan pelabuhan. Ia hidup dalam suhu air laut berkisar dari 6°C hingga 31 °C, dengan suhu optimum 9 °C hingga 19 °C. A. aurita lebih menyukai laut sedang dengan arus yang konsisten. Spesies ini telah ditemukan di perairan dengan kadar garam serendah 6 bagian per seribu.",
                "Para2" => "Hubungan antara hipoksia musim panas dan distribusi ubur-ubur bulan yang menonjol selama bulan-bulan musim panas (Juli dan Agustus) di mana suhu tinggi dan kadar oksigen terlarut yang rendah. Dari tiga kondisi lingkungan yang diuji, bahwa kadar oksigen terlarut bawah memiliki efek paling signifikan pada kelimpahan ubur-ubur bulan. Kelimpahan tertinggi ubur-ubur bulan terjadi ketika konsentrasi oksigen terlarut bawah lebih rendah dari 2,0 mg L -1. Ubur-ubur bulan menunjukkan toleransi yang kuat pada kondisi oksigen terlarut yang rendah, yang mengapa populasi mereka masih relatif tinggi selama bulan-bulan musim panas. Umumnya, hipoksia menyebabkan spesies untuk bergerak dari zona tanpa oksigen, namun hal ini tidak terjadi pada ubur-ubur bulan. Selanjutnya, tingkat kontraksi bel yang menunjukkan aktivitas makan ubur-ubur bulan, tetap konstan meskipun konsentrasi oksigen terlarut lebih rendah dari normal. Selama bulan Juli dan Agustus teramati bahwa agregasi ubur-ubur bulan dari 250 individu yang dikonsumsi sekitar 100% dari biomassa mesozooplankton di Laut Pedalaman Seto. Predator ikan besar lainnya yang juga hadir di perairan pantai ini tampaknya tidak menunjukkan toleransi tinggi yang sama untuk konsentrasi oksigen terlarut yang rendah. Memakan dan kinerja predator ikan ini secara signifikan menurun ketika konsentrasi oksigen terlarut sangat rendah. Hal ini memungkinkan terjadinya persaingan rendah antara ubur-ubur bulan dan predator ikan lainnya atas zooplankton. Konsentrasi oksigen terlarut yang rendah di perairan pesisir seperti Teluk Tokyo di Jepang dan Laut Pedalaman Seto terbukti menguntungkan bagi ubur-ubur bulan dalam hal makanan, pertumbuhan, dan kelangsungan hidup.",
            ]),
            'contentEn' => json_encode([
                "Para1" => "Aurelia aurita (also called the common jellyfish, moon jellyfish, moon jelly or saucer jelly) is a species of the genus Aurelia. All species in the genus are very similar, and it is difficult to identify Aurelia medusae without genetic sampling; most of what follows applies equally to all species of the genus.",
                "Para2" => "The jellyfish is almost entirely translucent, usually about 25-40 cm (10-16 in) in diameter, and can be recognized by its four horseshoe-shaped gonads, easily seen through the top of the bell. It feeds by collecting medusae, plankton, and mollusks with its tentacles, and bringing them into its body for digestion. It is capable of only limited motion, and drifts with the current, even when swimming. The species Aurelia aurita is found in the North, Black, Baltic and Caspian Seas, Northeast Atlantic, Greenland, northeastern USA and Canada, Northwest Pacific and South America. In general, Aurelia is an inshore genus that can be found in estuaries and harbors.",
                "Para3" => "Aurelia aurita lives in ocean water temperatures ranging from 6-31 °C (43-88 °F); with optimum temperatures of 9-19 °C (48-66 °F). It prefers temperate seas with consistent currents. It has been found in waters with salinity as low as 6 parts per thousand. The relation between summer hypoxia and moon jellyfish distribution is prominent during the summer months of July and August where temperatures are high and dissolved oxygen (DO) is low. Of the three environmental conditions tested, bottom DO has the most significant effect on moon jellyfish abundance. Moon jellyfish abundance is the highest when bottom dissolved oxygen concentration is lower than 2.0 mg L-1. Moon jellyfish show a strong tolerance to low DO conditions, which is why their population is still relatively high during the summer. Generally, hypoxia causes species to move from the oxygen depleted zone, but this is not the case for the moon jellyfish. Furthermore, bell contract rate, which indicates moon jellyfish feeding activity, remains constant although DO concentrations are lower than normal. During July and August, it is observed that moon jellyfish aggregations of 250 individuals consumed an estimated 100% of the mesozooplankton biomass in the Seto Inland Sea. Other major fish predators that are also present in these coastal waters do not seem to show the same high tolerance to low DO concentrations that the moon jellyfish exhibit. The feeding and predatory performance of these fish significantly decreases when DO concentrations are so low. This allows for less competition between the moon jellyfish and other fish predators for zooplankton. Low DO concentrations in coastal waters such as Tokyo Bay in Japan and the Seto Inland Sea prove to be advantageous for the moon jellyfish in terms of feeding, growth, and survival."
            ]),
            'editor' => "Init"
        ]);

        
        DB::table('article')->insert([
            'title' => "Universitas Tarumanagara",
            'contentId' => json_encode([
                "Para1" => "Universitas Tarumanagara adalah salah satu universitas swasta tertua yang berada di Jakarta, Indonesia. Nama universitas ini berasal dari nama kerajaan Tarumanagara. Universitas ini berdiri pada tanggal 1 Oktober 1959 dengan ditandai berdirinya "Perguruan Tinggi Ekonomi Tarumanagara" di bawah naungan "Yayasan Tarumanagara" yang berdiri pada tanggal 18 Juni 1959.",
                ]),
            'contentEn' => json_encode([
                "Para1" => "Pemikiran pertama untuk mendirikan suatu perguruan tinggi dicetuskan pada tahun 1957 oleh sekelompok sosiawan di lingkungan Perhimpunan Sosial Candra Naya yang pada waktu itu masih bernama Sin Ming Hui.Atas prakarsa Drs. Kwee Hwat Djien, pada tanggal 18 Juni 1959, mereka menyepakati untuk mendirikan suatu yayasan yang diberi nama Yayasan Tarumanagara yang kemudian dikukuhkan berdirinya melalui Akta Notaris E. Pondaag nomor 54 tanggal 11 September 1959.
Tarumanagara sebagai nama yayasan dan kemudian nama universitas diusulkan oleh P.K. Ojong pada rapat yayasan tanggal 3 Juli 1959. Usul itu didukung oleh Moh. Said.Nama Tarumanagara diambil dari nama kerajaan yang pernah berdiri di daerah yang kini menjadi Jawa Barat. Pada abad VI, di bawah pemerintahan Raja Purnawarman, kerajaan Tarumanagara mengalami masa jayanya. Kerajaan ini meninggalkan beberapa prasasti yang tersebar di daerah Jawa Barat sekarang termasuk di Jakarta, diantaranya, prasasti Ciaruteun yang terletak di lokasi pertemuan sungai Ciaruteun dan sungai Cisadane di daerah Bogor.Di samping badan hukum Sin Ming Hui, beberapa nama berikut termasuk pula sebagai pendiri yayasan ini. Mereka adalah Drs. Kwee Hwat Djien (H.K. Santoso), Mr. Auw Jong Peng Koen (P.K. Ojong), Drs. Oey Kwie Tek (Hendra Darmawan), Lim Toan Lok (Johannes Soewandi),Khoe Woen Sioe, Mr. Drs. Go Tie Siem, Dr. Liem Tjien Kiat ( Eddy L. Waworuntu), Drs. Lo Kiem Tjing, Drs.Lim Tjoeng Sen (Lutiarso Senoaji), Drs. Tjhio Jan Seng (Hadi Suryanto), R.Supangat Prawirokoesoemo,SH, Lim Tjong Tong, Oey Kim Sen, Go King Liong, Tjioe Bok San, dan Gan Hok Lin,SH (Ganis Suryahudaya). Setelah Yayasan Tarumanagara berdiri maka disusunlah pengurus yayasan yang pertama dengan formasi sebagai berikut: Ketua Drs. Kwee Hwat Djien (H.K. Santoso) Wakil ketua R. Supangat Prawirokoesoemo,SH Drs. Lo Kiem Tjing Penulis Drs. Domingus Sakarias Matakupan Wakil penulis Drs. Kho Han Tiong (A. Kahono) Bendahara Hazil Tanzil Wakil bendahara Drs. Tjhio Jan Seng (Hadi Suryanto) Para pembantu Mr. Auw Jong Peng Koen (P.K.Ojong) Mr.Drs. Go Tie Siem Go King Liong Oey Kim Sen R.M. Padmo Sumasto,SH Lie Beng Giok (L.B.G. Surjadinata) Maksud dan dan tujuan pendirian yayasan ini adalah " Mengembangkan dan meningkatkan mutu pendidikan, pengajaran, dan kebudayaan dalam masyarakat, dengan berpedoman pada pembentukan manusia Indonesia yang pandai dan berbudi luhur ".",
                "Para2" => "Untuk menilai mutu perguruan tinggi, Pemerintah telah membentuk Badan Akreditasi Nasional Perguruan Tinggi untuk mengakreditasi program studi di perguruan tinggi negeri dan swasta. Akreditasi ini mengenal beberapa peringkat yakni peringkat A, B, C, dan D. Terdapat sejumlah syarat untuk mencapai peringkat akreditasi itu. Pemenuhan syarat itu perlu dicapai melalui konsolidasi program studi yang ada.Dalam rangka konsolidasi ini, Universitas Tarumanagara berusaha meningkatkan jumlah dan jenjang jabatan akademik para dosen, meningkatkan prestasi belajar para mahasiswanya. Selain itu, Universitas Tarumanagara berusaha untuk meningkatkan mutu keilmuan di dalam universitas melalui pendidikan lanjut para dosen ke S3 serta meningkatkan kegiatan penelitian ilmiah.Mutu perguruan tinggi tercermin pada produk universitas yang pada saat ini diarahkan pada produk ilmuan, produk profesional, dan produk ilmu. Ilmuan dan profesional dihasilkan oleh pembelajaran di program studi sedangkan ilmu dihasilkan di lembaga penelitian, pengabdian pada masyarakat, dan jurnal ilmiah.Pada tahun 1998, Badan Akreditasi Nasional Perguruan Tinggi telah mengakreditasi sejumlah program studi di Universitas Tarumanagara, dengan hasil akreditasi peringkat A untuk progarm studi S1 manajemen, Program studi S1 Akuntansi, Program studi S1 Ilmu hukum, Program studi S1 Arsitektur, Program studi S1 Teknik Sipil, Program studi S1 Teknik Mesin, serta Program studi S1 pendidikan dokter dan baru-baru ini BAN PT mengakreditasi lagi Program studi Teknik Informatika dengan hasil terakreditasi peringkat A.Tahun 2022, mengikuti golongan akreditasi BAN-PT terbaru, Universitas Tarumanagara dinyatakan terakreditasi Unggul.",
                "Para3" => "Bagi Universitas Tarumanagara, tahun 1967 merupakan tahun awal kebangkitan kembali. Pada tahun itu, diresmikan penggunaan kampus di jalan Letjen. S.Parman. Pada waktu itu fakultas, jurusan, dan program studi dikonsolidasikan. Kecuali Fakultas bahasa-bahasa modern yang tidak berhasil bangkit kembali, fakultas lainnya dapat bertahan dan dikonsolidasikan."
            ]),
            'editor' => "Init"
        ]);

        DB::table('article')->insert([
            'title' => "Joko Widodo",
            'contentId' => json_encode([
                "Para1" => "Ir. H. Joko Widodo adalah presiden Indonesia yang mulai menjabat sejak tanggal 20 Oktober 2014. Terpilih dalam Pemilu Presiden 2014, Jokowi menjadi presiden Indonesia pertama yang bukan berasal dari elite politik atau militer Indonesia. Dia terpilih bersama Wakil Presiden Jusuf Kalla dan kembali terpilih bersama Wakil Presiden Ma'ruf Amin dalam Pemilu Presiden 2019. Sebelumnya, Jokowi pernah menjabat sebagai gubernur Jakarta sejak 15 Oktober 2012 hingga 16 Oktober 2014 didampingi Basuki Tjahaja Purnama sebagai wakil gubernur. Sebelumnya, ia adalah wali kota Surakarta, sejak tanggal 28 Juli 2005 hingga 1 Oktober 2012, didampingi F.X. Hadi Rudyatmo sebagai wakil wali kota. Dua tahun menjalani periode keduanya menjadi wali kota Surakarta, Jokowi ditunjuk oleh partainya, Partai Demokrasi Indonesia Perjuangan, untuk bersaing dalam Pilkada DKI Jakarta 2012 berpasangan dengan Basuki Tjahaja Purnama.",
                "Para2" => "Joko Widodo berasal dari keluarga sederhana, rumahnya pernah digusur sebanyak tiga kali ketika dia masih kecil, tetapi dia mampu menyelesaikan sekolahnya di Fakultas Kehutanan Universitas Gadjah Mada. Setelah lulus, dia menekuni profesinya sebagai pengusaha mebel. Karier politiknya dimulai dengan menjadi wali kota Surakarta pada tahun 2005. Namanya mulai dikenal setelah dianggap berhasil mengubah wajah Surakarta menjadi kota pariwisata, kota budaya, dan kota batik yang populer. Pada tanggal 20 September 2012, Jokowi berhasil memenangi Pilkada Jakarta 2012. Kemenangannya dianggap mencerminkan dukungan populer untuk seorang pemimpin yang muda dan bersih, meskipun umurnya sudah lebih dari 50 tahun.",
            ]),
            'contentEn' => json_encode([
                "Para1" => "Joko Widodo lahir dari pasangan Widjiatno Notomihardjo dan Sudjiatmi. Ia merupakan anak sulung dan putra satu-satunya dari empat bersaudara. Ia memiliki tiga orang adik perempuan bernama Iit Sriyantini, Ida Yati, dan Titik Relawati. Ia sebenarnya memiliki seorang adik laki-laki bernama Joko Lukito, tetapi meninggal saat persalinan. Sebelum berganti nama, Joko Widodo memiliki nama kecil Mulyono. Ayahnya berasal dari Karanganyar, sementara kakek dan neneknya berasal dari sebuah desa di Boyolali. Pendidikannya diawali dengan masuk SD Negeri 112 Tirtoyoso yang dikenal sebagai sekolah untuk kalangan menengah ke bawah.",
                "Para2" => "Dengan kesulitan hidup yang dialami, ia terpaksa berdagang, mengojek payung, dan menjadi kuli panggul untuk membiayai sendiri keperluan sekolah dan uang jajan sehari-hari. Saat anak-anak lain ke sekolah dengan sepeda, ia memilih untuk tetap berjalan kaki. Mewarisi keahlian bertukang kayu dari ayahnya, ia mulai bekerja sebagai penggergaji di umur 12 tahun. Jokowi kecil telah mengalami penggusuran rumah sebanyak tiga kali. Penggusuran yang dialaminya sebanyak tiga kali pada masa kecil mempengaruhi cara berpikirnya dan kepemimpinannya kelak setelah menjadi Wali Kota Surakarta saat harus menertibkan permukiman warga."
            ]),
            'editor' => "Init"
        ]);

        DB::table('article')->insert([
            'title' => "Steam",
            'contentId' => json_encode([
                "Para1" => "Steam adalah layanan distribusi digital permainan video oleh Valve. Ini diluncurkan sebagai klien perangkat lunak mandiri pada September 2003 sebagai cara bagi Valve untuk memberikan pembaruan otomatis untuk permainan mereka, dan diperluas untuk memasukkan permainan dari penerbit pihak ketiga. Steam juga telah berkembang menjadi etalase online berbasis web dan seluler digital. Steam menawarkan digital rights management (DRM), server pembuat pertandingan, streaming video, dan layanan jejaring sosial. Ini juga menyediakan pengguna dengan instalasi dan pembaruan permainan secara otomatis, dan fitur komunitas seperti daftar teman dan grup, penyimpanan awan, dan fungsi obrolan suara dan dalam permainan.",
                "Para2" => "Perangkat lunak ini menyediakan application programming interface (API) yang tersedia secara bebas yang disebut Steamworks, yang dapat digunakan pengembang untuk mengintegrasikan banyak fungsi Steam ke dalam produk mereka, termasuk perjodohan, pencapaian dalam permainan, transaksi mikro, dan dukungan untuk konten yang dibuat pengguna melalui Steam Workshop. Meskipun awalnya dikembangkan untuk digunakan pada sistem operasi Microsoft Windows, versi untuk macOS dan Linux kemudian dirilis. Aplikasi seluler juga dirilis untuk iOS, Android, dan Windows Phone pada tahun 2010-an. Platform ini juga menawarkan sejumlah kecil pilihan konten lainnya, termasuk perangkat lunak desain, perangkat keras, soundtrack permainan, anime, dan film.",
            ]),
            'contentEn' => json_encode([
                "Para1" => "Platform Steam adalah platform distribusi digital terbesar untuk PC gaming, menampung sekitar 75% ruang pasar pada tahun 2013. Pada 2017, pengguna yang membeli permainan melalui Steam berjumlah sekitar US$4,3 miliar, mewakili setidaknya 18% dari penjualan permainan PC global. Layanan ini memiliki lebih dari 34.000 permainan pada tahun 2019, dengan lebih dari 95 juta pengguna aktif bulanan. Keberhasilan Steam telah menyebabkan pengembangan produk microconsole Steam Machine, yang meliputi sistem operasi SteamOS dan Steam Controller.",
                "Para2" => "Layanan utama Steam adalah memungkinkan penggunanya mengunduh permainan dan perangkat lunak lain yang mereka miliki di perpustakaan perangkat lunak virtual mereka ke komputer lokal mereka sebagai file cache permainan (GCF). Awalnya, Valve diharuskan menjadi penerbit untuk permainan-permainan ini karena mereka memiliki akses tunggal ke database dan mesin Steam, tetapi dengan diperkenalkannya kit pengembangan perangkat lunak (SDK) Steamworks pada Mei 2008, siapa pun berpotensi menjadi penerbit untuk Steam, di luar keterlibatan Valve untuk mengurasi permainan di layanan."
            ]),
            'editor' => "Init"
        ]);

        DB::table('article')->insert([
            'title' => "Visual Studio Code",
            'contentId' => json_encode([
                "Para1" => "Visual Studio Code (disingkat VSCode) adalah perangkat lunak penyunting kode sumber buatan Microsoft untuk Linux, macOS, dan Windows. Visual Studio Code menyediakan fitur seperti penyorotan sintaksis, penyelesaian kode, kutipan kode, merefaktor kode, pengawakutuan, dan Git. Microsoft merilis sumber kode Visual Studio Code di repositori GitHub dengan lisensi MIT, sedangkan biner yang dibangun oleh Microsoft tidak dirilis dengan lisensi MIT dan merupakan perangkat lunak berpemilik.",
                "Para2" => "Visual Studio Code merupakan penyunting kode-sumber yang dapat digunakan untuk beragam bahasa pemrograman, termasuk Java, JavaScript, Go, Node.js, Python dan C++. Visual Studio Code memperkerjakan komponen penyunting yang sama (namakode "Monaco") yang digunakan di Azure DevOps (awalnya dippangil Visual Studio Online dan Visual Studio Team Services).",
            ]),
            'contentEn' => json_encode([
                "Para1" => "Sebagai ganti dari sistem proyek, VSCode memungkinkan pengguna untuk membuka satu atau lebih banyak direktori, yang dapat disimpan di ruang kerja untuk digunakan ulang nanti. Ini memungkinkan untuk beroperasi sebagai penyunting kode languange agnostic untuk semua bahasa. VSCode mendukung banyak bahasa pemrograman dan sekumpulan fitur yang berbeda dari setiap bahasa. Berkas dan map yang tidak diingikan dapat di kecualikan dari pohon proyek melalui pengaturan proyek tersebut. Kebanyakan fitur VSCode tidak di terekspos melalui menu atau tampilan pengguna tetapi dapat diakses melalui command palette.",
            ]),
            'editor' => "Init"
        ]);

        DB::table('article')->insert([
            'title' => "Boeing 737",
            'contentId' => json_encode([
                "Para1" => "Boeing 737 merupakan salah satu jenis pesawat komersial berbadan sempit dengan mesin ganda (twin jet) yang diproduksi oleh Pabrik Boeing di Seattle, Amerika Serikat. Awalnya pesawat ini merupakan pengembangan versi murah dari Boeing 707 dan 727 dengan kapasitas yang lebih sedikit dan berjarak pendek. 737 adalah produk yang paling laris di pasar penerbangan dunia dengan penjualan lebih dari 15,533 unit hingga bulan Maret 2019 dengan pesanan yang belum terkirim mencapai 4703 unit pada bulan Maret 2019. Boeing 737 merupakan pesaing utama dari pesawat berlorong tunggal keluaran Airbus yaitu A320.",
            ]),
            'contentEn' => json_encode([
                "Para1" => "Pada era 60an, pesawat penumpang berkapasitas rendah dan jarak dekat didominasi oleh dan. ketika itu dapat dikatakan tertinggal dibanding dengan pesaing-pesaingnya dalam pembuatan pesawat berjarak dekat. Pada 1964, memulai program pembuatan 737 tetapi, untuk menghemat waktu menggunakan rancangan Boeing 707 dan 727 dalam pembangunan 737. Hal ini adalah satu kelebihan bagi 737 karena lebar fuselage 737 yang didesain ini mampu memuat enam tempat duduk, lebih satu dari.",
                "Para2" => "737-100 adalah desain pertama dan karena bentuknya yang pendek dan gemuk, menggelarkannya "FLUF" untuk 'Fat Little Ugly Fella' di mana pada masa yang sama, industri penerbangan memanggilnya 'Baby Boeing'. Seri-100 dan -200 dapat dibedakan dengan seri-seri yang lain dengan melihat kedudukan mesinnya yang bercantum dengan sayap pesawat. Manakala Pratt and Whitney JT8D adalah mesin asal untuk model ini"
                "Para3" => "Penerbangan perdana 737 (sebuah pesawat seri 100) dilaksanakan pada dan penerbangan komersial pada Februari 1968 oleh. Bagi 737-200, penerbangan perdananya ialah pada. Akan tetapi, hanya 30 pesawat 737-100 saja yang diproduksi."
            ]),
            'editor' => "Init"
        ]);

        DB::table('article')->insert([
            'title' => "Bumi Serpong Damai",
            'contentId' => json_encode([
                "Para1" => "Bumi Serpong Damai (atau BSD City) adalah salah satu kota terencana di Indonesia yang terletak di Banten. BSD City adalah salah satu kota satelit dari Jakarta yang awalnya ditujukan untuk menjadi kota mandiri, di mana semua fasilitas disediakan, mulai dari kawasan industri, perkantoran, perdagangan, pendidikan, wisata, hingga perumahan. Saat ini, nama "BSD" tidak mengacu pada sebuah singkatan, tetapi lebih berupa kata yang berdiri sendiri. Berbeda dengan pengembang sebelumnya, Sinar Mas Group lebih mempopulerkan nama "BSD City", serta menambahkan slogan Big City. Big Opportunity untuk tujuan promosi.",
                "Para2" => "BSD City merupakan proyek kota terencana dengan total luas lahan terbesar di Indonesia, yaitu seluas 6.000 hektar. Tahap pengembangan BSD City dibagi menjadi tiga tahap. Tahap I seluas 1.300 hektare. Tahap II akan dikembangkan seluas 2.400 hektare, dan tahap III akan dikembangkan seluas 2.300 hektare. BSD City dilengkapi dengan sejumlah pusat perbelanjaan, seperti BSD Plaza, ITC BSD, BSD Junction, Giant Hypermarket BSD, AEON Mall dan Teraskota. Di sini juga terdapat sejumlah tempat rekreasi, seperti Ocean Park Water Adventure seluas 7,5 hektaree yang merupakan salah satu water park tematik terbesar di Asia Tenggara. BSD City akan dihubungkan dengan lima pintu tol, yang mana dua di antaranya sudah dibuka sejak tahun 1999.",
            ]),
            'contentEn' => json_encode([
                "Para1" => "Pada tanggal 16 Januari 1989, Menteri Dalam Negeri Rudini meresmikan dimulainya pengembangan kota mandiri ini di atas lahan yang sebelumnya adalah hamparan hutan karet yang tidak lagi produktif. Hingga tahun 1988, jalan menuju hutan karet tersebut hanya berupa jalan tanpa aspal. Di musim hujan, jalan tersebut berubah menjadi kubangan, dan pada musim kemarau, debu-debu beterbangan di jalan.",
                "Para2" => "Pengembangan Bumi Serpong Damai dilakukan oleh PT Bumi Serpong Damai (PT BSD) yang awalnya sahamnya dimiliki oleh sebelas perusahaan swasta dengan investasi sebesar Rp 3,2 triliun. Sebelas perusahaan tersebut tergabung dalam Sinar Mas Group, Salim Group, Metropolitan Group, dan Pembangunan Jaya. Akses ke Bumi Serpong Damai pun perlahan-lahan dibuka, karena saat itu, baru ada Jalan Tol Jakarta-Merak. Jarak Bumi Serpong Damai pun masih relatif jauh dari pusat kota Jakarta, walaupun bisa dijangkau dengan angkutan umum, seperti bus patas yang jumlahnya masih terbatas. Nama-nama klaster perumahan yang dikembangkan saat itu antara lain Giri Loka, Puspita Loka, Griya Loka, Anggrek Loka, Nusa Loka, dan Kencana Loka.",
            ]),
            'editor' => "Init"
        ]);

        DB::table('article')->insert([
            'title' => "Bank Central Asia",
            'contentId' => json_encode([
                "Para1" => "PT Bank Central Asia Tbk (disingkat BCA) adalah bank swasta terbesar di Indonesia. Bank ini didirikan pada 21 Februari 1957 dan pernah menjadi bagian penting dari Salim Group. Sekarang bank ini dimiliki oleh salah satu grup produsen rokok terbesar keempat di Indonesia, Djarum.",
            ]),
            'contentEn' => json_encode([
                "Para1" => "PT Bank Central Asia Tbk didirikan pada 10 Agustus 1955 dengan nama NV Perseroan Dagang dan Industrie Semarang Knitting Factory. Awalnya, perusahaan ini bukanlah berbisnis perbankan, melainkan sebuah perusahaan tekstil di Semarang. Tidak lama kemudian, perusahaan tekstil tersebut berubah menjadi sebuah perusahaan bank pada 12 Oktober 1956 bernama NV Bank Asia. Namanya kemudian berganti menjadi Central Bank Asia pada 13 Februari 1957 dan NV (kemudian PT) Bank Centraal Asia pada 21 Februari 1957. Pada hari yang sama, bank ini mulai beroperasi, yang tanggalnya kemudian ditetapkan sebagai hari jadi BCA. Bank Centraal Asia kemudian mendapat izin pemerintah untuk beroperasi sebagai bank pada 14 Maret 1957.",
                "Para2" => "Kepemilikan Salim Group dalam banknya ini harus berakhir pada akhir 1990-an akibat sejumlah krisis. Sebenarnya, tanda-tanda itu sudah muncul di akhir 1997. Di saat krisis finansial Asia 1997 mulai menimpa Indonesia, di tanggal 14 November 1997 (dua minggu setelah likuidasi 16 bank), tersiar kabar burung dari Medan bahwa Liem sebagai pengendali BCA wafat dan cabangnya di Singapura ditutup. Sontak saja, masyarakat yang baru trauma atas likuidasi bank, menyerbu kantor cabangnya dan menarik dananya (bank run/rush) yang mencapai Rp 500 miliar. Untuk menepis kabar tersebut, Liem yang saat itu ada di Singapura, kembali ke Jakarta dan hadir di peluncuran produk baru Indomobil untuk meyakinkan masyarakat lewat siaran televisi bahwa ia sehat-sehat saja.",
                "Para3" => "Setelah rumor itu pergi, Salim Group mulai menjajaki rencana konsolidasi bank dalam menghadapi krisis moneter. Pada tanggal yang sama saat rumor palsu tentang kematian Liem beredar, anaknya Anthony menyepakati pembelian 19% saham Bank Danamon yang direncanakan akan ditingkatkan bagi menyehatkan keuangan bank swasta tersebut. Tidak hanya itu, juga muncul wacana akan adanya merger antara BCA dengan sejumlah anak usahanya di bidang perbankan, seperti Bank Windu Kentjana, Bank Multicor, Bank Risjad Salim Internasional dan Bank Yama. Meskipun demikian, rencana tersebut kemudian hanya menjadi wacana, dan ide meningkatkan kepemilikan saham di Bank Danamon sendiri harus dibatalkan akibat bank tersebut menderita kesulitan likuiditas dan harus diambilalih Badan Penyehatan Perbankan Nasional (BPPN) pada April 1998.",
            ]),
            'editor' => "Init"
        ]);

        DB::table('article')->insert([
            'title' => "Adidas",
            'contentId' => json_encode([
                "Para1" => "Adidas AG (juga dikenal sebagai adidas) adalah sebuah perusahaan sepatu Jerman. Perusahaan ini dinamakan atas pendirinya, Adolf (Adi) Dassler, yang mulai memproduksi sepatu pada 1920-an di Herzogenaurach dekat Nuremberg. Rancangan baju dan sepatu perusahaan ini biasanya termasuk tiga strip paralel dengan warna yang sama, dan motif yang sama digunakan sebagai logo resmi adidas. Adidas adalah perusahaan pakaian olahraga terbesar di Eropa dan kedua terbesar di dunia setelah Nike.",
                "Para2" => "Rudolf Dassler, adik Adi, mendirikan perusahaan saingan, Puma. Pada Agustus 2005, Adidas mengakuisi rivalnya, Reebok, dalam upaya memperketat persaingan dengan Nike.",
            ]),
            'contentEn' => json_encode([
                "Para1" => "Selama 68 tahun lamanya grup Adidas telah menjadi bagian dari dunia olahraga di segala bidangnya dengan menawarkan sepatu, pakaian serta beragam aksesori pelengkap olahraga yang bernilai seni pada setiap produknya. Sekarang, grup Adidas telah mengglobalisasi dan menguasai di bidang industri produk olahraga dan menawarkan portfolio yang begitu luas dari segi produk di seluruh dunia. Strategi grup Adidas sangatlah simpel: memperkuat bran secara terus menerus dan mengimprovisasi posisi kompetitif serta keuangan mereka. Aktivitas perusahaan dan lebih dari 150 cabangnya dipantau langsung oleh pemimpin grup di Herzogenaurach, Jerman. Tertanggal 31 Desember 2009, grup Adidas tercatat mempekerjakan sebanyak 38.982 orang selama setahun penuh.",
                "Para2" => "Juga ada pendapat, bahwa sebetulnya Adidas adalah sebuah singkatan dari sebuah kalimat, yaitu "All day I dream about sports" (Tiap hari aku bermimpi tentang olahraga). Pendapat ini disetujui banyak orang mengingat bila tiap huruf pertama dari kata yang terkandung dalam kalimat diambil lalu disusun, akan membentuk kata Adidas, dan juga maknanya yang mendukung semangat olahraga.",
            ]),
            'editor' => "Init"
        ]);

        DB::table('article')->insert([
            'title' => "Nintendo",
            'contentId' => json_encode([
                "Para1" => "Nintendo Co., Ltd.[a] (Nasdaq: NTDOY, TYO: 7974) adalah konsumer elektronik multinasional dan perusahaan permainan video yang berkantor pusat di Kyoto. Awalnya merupakan perusahaan kartu yang kemudian berkembang dari perusahaan mainan hingga menjadi perusahaan permainan video, Nintendo merupakan salah satu perusahaan permainan video terbesar di dunia dari kapitalisasi pasar, menciptakan beberapa waralaba permainan yang terkenal dan yang terlaris sepanjang masa, seperti Mario, The Legend of Zelda, Animal Crossing, dan Pokemon.",
                "Para2" => "Didirikan pada 23 September 1889 oleh Fusajiro Yamauchi, awalnya perusahaan tersebut memproduksi kartu buatan tangan hanafuda. Pada tahun 1963, perusahaan tersebut telah mencoba beberapa bisnis ceruk kecil, seperti layanan taksi dan hotel cinta. Meninggalkan usaha sebelumnya demi mainan pada tahun 1960-an, Nintendo berkembang menjadi perusahaan permainan video pada dekade 1970-an. Ditambah sejak 1980-an dari divisi besar seperti Nintendo of America dan Nintendo of Europe, pada akhirnya menjadi salah satu industri yang paling berpengaruh dan perusahaan paling yang berharga di Jepang dengan jumlah pasar sebesar $37 miliar pada tahun 2018.",
            ]),
            'contentEn' => json_encode([
                "Para1" => "Nintendo didirikan sebagai perusahaan kartu remi oleh Fujisaro Yamauchi pada 23 September 1889. Berkantor pusat di Kyoto, perusahaan tersebut memproduksi dan memasarkan kartu hanafuda. Kartu buatan tangan tersebut kemudian menjadi populer, dan Yamauchi memberi pekerja asisten untuk memproduksi massal kartu untuk memenuhi permintaan. Perusahaan tersebut secara formal dibentuk dengan kemitraan tanpa batas berjudul Yamauchi Nintendo & Co. Ltd. pada tahun 1933. Nama tersebut berubah menjadi Nintendo Playing Card Co. Ltd. pada tahun 1951. Nintendo melanjutkan memanufaktur kartu bermain di Jepang dan mengorganisir turnamen contact bridge tersendiri sebagai "Nintendo Cup". Kata Nintendo dapat diartikan sebagai "tinggalkan keberuntungan ke surga", atau secara alternatif "kuil hanafuda gratis".",
                "Para2" => "Pada tahun 1956, Hiroshi Yamauchi, cucu dari Fusajiro Yamauchi, mengunjungi AS untuk berbicara dengan United States Playing Card Company, sebuah manufaktur kartu dominan disana. Ia telah menemukan perusahaan permainan kartu terbesar di dunia hanya memiliki kantor kecil. Realisasi Yamauchi bahwa bisnis permainan kartu hanya memiliki potensial tersebut merupakan titik balik. Ia kemudian meminta izin untuk menggunakan karakter Disney pada permainan kartu untuk mendorong penjualan.",
                "Para3" => "Usaha pertama Nintendo ke dalam industri permainan video adalah mendapatkan hak untuk mendistribusikan konsol permainan video Magnavox Odyssey di Jepang pada tahun 1974. Nintendo mulai memproduksi perangkat kerasnya sendiri pada tahun 1977, dengan konsol permainan video rumahan Color TV-Game. Empat versi konsol ini diproduksi, masing-masing termasuk variasi dari satu permainan; misalnya, Color TV Game 6 menampilkan enam versi Light Tennis.",
            ]),
            'editor' => "Init"
        ]);
    }
}
